# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: svcs - configuring Cloud Services daemon
  template: src=svcs/csd.conf.j2
            dest=/etc/csd.conf
            owner=root
            group=root
            mode=0644
            backup=yes


- name: svcs - configuring Cloud Services JS
  template: src=svcs/config.js.j2
            dest=/var/lib/csd/public/config.js
            owner=root
            group=root
            mode=0644
            backup=yes


- name: svcs - configuring Redis
  template: src=svcs/redis.conf.j2
            dest=/etc/redis.conf
            owner=root
            group=root
            mode=0644
            backup=yes


- name: svcs - configuring InfluxDB
  template: src=svcs/config.toml.j2
            dest=/opt/influxdb/shared/config.toml
            owner=influxdb
            group=influxdb
            mode=0644
            backup=yes


# Handlers:

- name: wipe-out-data-restart-influxdb
  shell: if [ -d /opt/influxdb/shared/data ]; then rm -rf /opt/influxdb/shared/data ; sync ; /etc/init.d/influxdb restart ; fi
  when: is_packer != 'yes'


- pause:
    seconds: 3


- name: restart-cloudservices
  service: name=csd state=restarted enabled=yes
  when: is_packer != 'yes'
