# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# References:
# http://docs.openstack.org/mitaka/install-guide-ubuntu/nova-controller-install.html

- include: openstack-nova-init.yml
  when: deployment_mode == 'yes'


- name: Installing Nova
  apt: name={{item}} state=latest
  with_items:
    - nova-api
    - nova-cert
    - nova-scheduler
    - nova-conductor
    - nova-spiceproxy
    - nova-consoleauth
  notify: restart-nova


- name: Removing non-used sqlite database
  file: path=/var/lib/nova/nova.sqlite state=absent
  notify: restart-nova


- name: Updating nova.conf
  template: src={{openstack_release}}/nova.conf
            dest=/etc/nova/nova.conf
            owner=nova
            group=nova
            mode=0640
            backup=yes
  when: item.os_project == "nova"
  with_items: '{{mysql_databases}}'
  notify: restart-nova


- name: Populating Nova Database
  shell: su -s /bin/sh -c "nova-manage db sync" nova


- name: Populating Nova API Database
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova
