# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference:
# http://docs.openstack.org/mitaka/install-guide-ubuntu/keystone-install.html

- name: Installing Keystone Server
  apt: name={{item}} state=latest
  with_items:
    - keystone


- name: Stopping and disabling Keystone (it runs under Apache)
  service: name=keystone state=stopped enabled=no


- name: Removing non-used sqlite database
  file: path=/var/lib/keystone/keystone.db state=absent


- name: Updating keystone.conf
  template: src={{openstack_release}}/keystone.conf
            dest=/etc/keystone/keystone.conf
            owner=root
            group=root
            mode=0644
            backup=yes
  when: item.os_project == "keystone"
  with_items: '{{mysql_databases}}'
  notify: reload-apache2


- name: Populating Keystone Database
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone


- name: Initialize Fernet keys
  shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone


- name: Creating Apache Keystone Virtual Host - Public
  copy: src=wsgi-keystone-public.conf
        dest=/etc/apache2/sites-available/wsgi-keystone-public.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  notify: reload-apache2

- name: Creating Apache Keystone Virtual Host - Internal
  copy: src=wsgi-keystone-internal.conf
        dest=/etc/apache2/sites-available/wsgi-keystone-internal.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  notify: reload-apache2

- file: src=/etc/apache2/sites-available/wsgi-keystone-public.conf
        dest=/etc/apache2/sites-enabled/wsgi-keystone-public.conf
        owner=root
        group=root
        state=link

- file: src=/etc/apache2/sites-available/wsgi-keystone-internal.conf
        dest=/etc/apache2/sites-enabled/wsgi-keystone-internal.conf
        owner=root
        group=root
        state=link


- meta: flush_handlers


- include: openstack-keystone-init.yml
  when: deployment_mode == 'yes'


- name: Updating keystone-paste.ini
  copy: src={{openstack_release}}/keystone-paste.ini
        dest=/etc/keystone/keystone-paste.ini
        owner=root
        group=root
        mode=0644
        backup=yes
  notify: reload-apache2


- meta: flush_handlers


- name: Copying OpenStack RC files for your current system user
  include: openrc-files.yml
