heat_template_version: 2014-10-16  

description: A simple auto scaling group.  

outputs: null

parameters:

  config: {default: /sandvine/blank-config, description: Config, label: Configuration
      (e.g. pre-population SandScript), type: string}

  pts_flavour: {default: m1.medium, description: PTS Flavour, label: PTS Flavour (default
      'm1.medium'), type: string}

  pts_image: {default: PTS_7.30.08_2, description: PTS Image, label: PTS Image (default
      'PTS_7.30.08_2'), type: string}

  public_network: {default: ext-net, description: Public Network with Floating IP
      addresses, label: Public External Network, type: string}

  ssh_key: {default: default, description: 'If you have not created your key, please
      go to

      Project/Compute/Access & Security, and either import

      one or create one. If you create it, make sure you keep

      the downloaded file (as you don''t get a second chance)

      ', label: Your SSH keypair name (pre-create please!), type: string}

resources:

  ctrl_net:
    properties:
      name:
        str_replace:
          params:
            $stack_name: {get_param: 'OS::stack_name'}
          template: $stack_name-ctrl-net
    type: OS::Neutron::Net

  ctrl_subnet:
    properties:
      allocation_pools:
      - {end: 192.168.224.254, start: 192.168.224.20}
      cidr: 192.168.224.0/24
      enable_dhcp: true
      name:
        str_replace:
          params:
            $stack_name: {get_param: 'OS::stack_name'}
          template: $stack_name-ctrl-subnet
      network_id: {get_resource: ctrl_net}
    type: OS::Neutron::Subnet

  service_net:
    properties:
      name:
        str_replace:
          params:
            $stack_name: {get_param: 'OS::stack_name'}
          template: $stack_name-service
    type: OS::Neutron::Net

  service_subnet:
    properties:
      allocation_pools:
      - {end: 192.168.240.254, start: 192.168.240.20}
      cidr: 192.168.240.0/24
      enable_dhcp: true
      name:
        str_replace:
          params:
            $stack_name: {get_param: 'OS::stack_name'}
          template: $stack_name-service-subnet
      network_id: {get_resource: service_net}
    type: OS::Neutron::Subnet

  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 2
      max_size: 5
      min_size: 1
      resource:
        type: OS::Nova::Server
        properties:
          admin_user: svuser
          flavor: {get_param: pts_flavour}
          image: {get_param: pts_image}
          key_name: {get_param: ssh_key}
          metadata:
          name:
            str_replace:
              params:
                $stack_name: {get_param: 'OS::stack_name'}
              template: $stack_name-pts
          networks:
          - network: {get_resource: ctrl_net}
          - network: {get_resource: service_net}
          user_data: "#cloud-config\nsystem_info:\n  default_user:\n    name: \"sandvine\"\
            \nchpasswd:\n  list: |\n    root:sandvine\n    sandvine:sandvine\n  expire:\
            \ False\n"
          user_data_format: RAW
